### ISSUE TITLE
gotopp.org is down

### ISSUE THREAD

**Issue by ColinPitrat** [Sidoine/gotopp#5]
Sorry if this is not the right place to report it, but I really don't know what to do.
I'm lost, please advise.

This needs to be fixed as soon as possible.

**Comment by ColinPitrat** [comment]
Any news ? This is getting very worrying.

**Comment by ColinPitrat** [comment]
Oh my god, I still can't access it.

**Comment by ColinPitrat** [comment]
I'm thinking of switching to another language right now.

**Comment by ColinPitrat** [comment]
OK that's it, I migrated my whole codebase to whitespace.

**Comment by Sidoine** [comment]
I guess I forgot to renew the domain name. I don't know what to say, it's the biggest mistake in my life.

**Comment by Sidoine** [comment]
I'm depressed now.

**Comment by Sidoine** [comment]
Oh I still got it. What a waste of good money. I guess I have to direct it to the right web site now. Maybe tomorrow

**Comment by Sidoine** [comment]
It's time to migrate the code base back to GOTO++.

**Comment by HayateLaTech** [comment]
I mean.. the website is not really down, but it sure isn't working right now! 😸 The curse++ sure is all apparent.

![image](https://github.com/user-attachments/assets/e99bc22d-1d89-4142-b072-7f4a08fc6c8f)

**Comment by Sidoine** [comment]
Thanks! I rebuilt the website, it should be running now.
